-- MySQL Script generated by MySQL Workbench
-- seg 24 jan 2022 18:35:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema minhoPark
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema minhoPark
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `minhoPark` ;
USE `minhoPark` ;

-- -----------------------------------------------------
-- Table `minhoPark`.`Parques`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minhoPark`.`Parques` (
  `idParque` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Imagem` LONGBLOB NULL,
  `Endereco` VARCHAR(200) NOT NULL,
  `Coordenadas` VARCHAR(45) NOT NULL,
  `NrCriticas` INT NOT NULL,
  `Rating` FLOAT NOT NULL,
  PRIMARY KEY (`idParque`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minhoPark`.`Categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minhoPark`.`Categorias` (
  `idCategoria` VARCHAR(45) NOT NULL,
  `Icone` LONGBLOB NULL,
  PRIMARY KEY (`idCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minhoPark`.`Horarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minhoPark`.`Horarios` (
  `idHorario` INT NOT NULL,
  `Parques_idParque` INT NOT NULL,
  `HoraDeAbertura` TIME NOT NULL,
  `HoraDeEncerramento` TIME NOT NULL,
  `Dia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idHorario`),
  INDEX `fk_Horários_Parques1_idx` (`Parques_idParque` ASC) VISIBLE,
  CONSTRAINT `fk_Horários_Parques1`
    FOREIGN KEY (`Parques_idParque`)
    REFERENCES `minhoPark`.`Parques` (`idParque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `minhoPark`.`Parques_has_Categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `minhoPark`.`Parques_has_Categorias` (
  `Parques_idParque` INT NOT NULL,
  `Categorias_idCategoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Parques_idParque`, `Categorias_idCategoria`),
  INDEX `fk_Parques_has_Categorias_Categorias1_idx` (`Categorias_idCategoria` ASC) VISIBLE,
  INDEX `fk_Parques_has_Categorias_Parques1_idx` (`Parques_idParque` ASC) VISIBLE,
  CONSTRAINT `fk_Parques_has_Categorias_Parques1`
    FOREIGN KEY (`Parques_idParque`)
    REFERENCES `minhoPark`.`Parques` (`idParque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Parques_has_Categorias_Categorias1`
    FOREIGN KEY (`Categorias_idCategoria`)
    REFERENCES `minhoPark`.`Categorias` (`idCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
